### ISSUE TITLE
When user has no regions, cannot get host, throws cannot read property error

### ISSUE THREAD

**Issue by gunn4r** [tcncloud/protoc-gen-state#7]
In the generated epics:
```var host = store.getState().user.selectedRegion.value.slice(0, -1) + ':9090';```

Will fail with ```Cannot read property slice of undefined``` when a user has no regions (and thus no selected region). 

Need to throw a better error when the host can't be set properly.

**Comment by hectim** [comment]
oh yeah that `slice(0, -1)` every time is a bad bit of logic. I guess it should check it exists, check for a slash, and throw errors otherwise. Will include the change in next big push related to #6
